include: package:lint/analysis_options.yaml

# Not happy with the default? Customize the rules depending on your needs. 
# Here are some examples:
linter:
  rules:
    # Make constructors the first thing in every class
    sort_constructors_first: true

    # Good packages document everything
    public_member_api_docs: true

    # Back to the 80s
    lines_longer_than_80_chars: true